[build]
  command   = "npm run build"
  publish   = "dist/"
  functions = ""          # no functions needed

# (Optional) catch-all for SPA-like routing:
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
