[build]
  command   = "npm install"
  publish   = "public"
  functions = "functions"

# Catch all requests under /proxy and forward them to the Lambda
[[redirects]]
  from   = "/proxy/*"
  to     = "/.netlify/functions/proxy"
  status = 200
  force  = true
